version: '3'
services:
  webapp:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: uploader-service
    image: 'uploader-service'
    restart: 'no'
    ports:
      - '8028:80'
    volumes:
      - './:/var/www/'
      - './docker/php/php.ini:/etc/php/8.1/apache2/php.ini'
      - './docker/php/php.ini:/etc/php/8.1/cli/php.ini'
    links:
      - mariadb
  mariadb:
    image: 'mariadb:10.3.28'
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'database'
    volumes:
      - /var/lib/mysql
  adminer:
    image: adminer
    restart: 'no'
    links:
      - mariadb
    ports:
      - '8029:8080'

